### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by majuca** [matasarei/JsonRPC#13]
Hi,

Could be great to have the possibility to add more CURL options for example proxy options (CURLOPT_PROXY, CURLOPT_PROXYPORT) or stream options if CURL isn't installed.

Something like this:

public function execute($payload, array $headers = [], array $option =[]) {
...

**Comment by matasarei** [comment]
Hi @majuca . Right now I don't have time to implement new features. I'll try to find some time next week. If you have clear view about it, you can try write some code by yourself, or at least give more context.

**Comment by majuca** [comment]
Hi,

Something like this:


[HttpClient.txt](https://github.com/matasarei/JsonRPC/files/3504518/HttpClient.txt)

**Comment by lucc** [comment]
@majuca you could also post the `git diff` in a code block, that would be easier to read.

**Comment by majuca** [comment]
Hi, I will do a pull request. I come back asap.

**Comment by matasarei** [comment]
https://github.com/matasarei/JsonRPC/pull/15
