### ISSUE TITLE
Symfony

### ISSUE THREAD

**Issue by 3r1d** [matasarei/JsonRPC#16]
Is it possible to use this library with Symfony ?

**Comment by 3r1d** [comment]
Thanks for your quick answer.

Not asking for a bundle, but regarding HTTP protocol, I was wondering if the library was running it's own standalone http server,
or if it can be integrated within an existing http server (i.e. Symfony).

I will try to plug it in Symfony, inside a controller, and pass it the Http Request.

**Comment by lucc** [comment]
We are using it behind a lumen router at work.

**Comment by matasarei** [comment]
Check this: https://github.com/matasarei/json_rpc_demo/commit/fb856d1d9840eb345e51548e04fb9292412538ee

**Comment by 3r1d** [comment]
Thank you guys !

It works like a charm.

The diff was super helpful.


For the record, I used this command for the test:
`
$ curl -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id":"id","method":"hello_world","params":[]}' http://localhost:8000/rpc

{"jsonrpc":"2.0","result":"Hello World!","id":"id"}
